### ISSUE TITLE
Add mic/camera/screenshare/chat/participants UI

### ISSUE THREAD

**Issue by vincentfretin** [c-frame/aframe-gltf-model-plus#34]
Add mic/camera/screenshare/chat/participants UI in the example, using a simple script tag and a single or several web components.
See my comment https://github.com/c-frame/aframe-gltf-model-plus/issues/28#issuecomment-2010339761 and issue https://github.com/networked-aframe/networked-aframe/issues/423

Related issues:
- https://github.com/networked-aframe/naf-janus-adapter/issues/67
- https://github.com/c-frame/aframe-gltf-model-plus/issues/16
- https://github.com/networked-aframe/naf-valid-avatars/issues/18
- https://github.com/networked-aframe/naf-valid-avatars/issues/19

**Comment by uhunkler** [comment]
I tried the ui-components branch and got the following error in Chrome on a mac:

Networked-Aframe Connecting...
networked-aframe.min.js:1 TypeError: Cannot read properties of undefined (reading 'getUserMedia')
    at h.value (networked-aframe.min.js:1:32360)
    at networked-aframe.min.js:1:27571
    at new Promise (<anonymous>)
    at h.value (networked-aframe.min.js:1:27542)
    at t.value (networked-aframe.min.js:1:10213)
    at n.connect (networked-aframe.min.js:1:74485)
    at v.emit (a-node.js:293:10)
    at HTMLButtonElement.onclick (playground/:197:36) 'failure to connect'
value @ networked-aframe.min.js:1
value @ networked-aframe.min.js:1
Promise.catch (async)
value @ networked-aframe.min.js:1
value @ networked-aframe.min.js:1
connect @ networked-aframe.min.js:1
emit @ a-node.js:293
onclick @ playground/:197

**Comment by vincentfretin** [comment]
Did you run 
```sh
npm install
npm start
```
and went to http://localhost:8080 ?

**Comment by vincentfretin** [comment]
I merged #37 already but this is not finished. I'm working a naf-users-button to show the participants in the room. I'll probably rename the naf-nametag-solidjs repo to naf-ui-components, expose the src/components files to be used a ES modules for naf-valid-avatars example. And also create a naf-valid-avatars web component to easily integrate it here.

**Comment by uhunkler** [comment]
I didn't run »npm install« - I just updated and ran the project. Now after you merged it in the main branch  networking runs without issues. Great.

**Comment by vincentfretin** [comment]
I added the new naf-users-button web component in the example.
